/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp3_urban;

import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author nejo
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ejercicio 1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Ejercicio 2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Ejercicio 3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Ejercicio 4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ArrayList<Double> notas = new ArrayList<Double>();
        notas.add(10.00d);
        notas.add(5.51d);
        notas.add(8.21d);
        notas.add(3.63d);
        notas.add(7.21d);
        notas.add(6.15d);
        notas.add(9.00d);
        notas.add(8.00d);
        notas.add(7.81d);
        notas.add(8.05d);
        notas.add(6.60d);
        notas.add(4.15d);
        notas.add(4.15d);
        notas.add(4.15d);
        notas.add(4.15d);
        
        double x = 0.00d; /*Variable "x" para que almacene la suma de las notas*/
        for(int i = 0;i<notas.size();i++){ /*bucle for para las notas, El método size() devuelve el número de elementos actualmente presentes en la colección*/
            x+=notas.get(i);
        }
        x/= notas.size(); /*divido la suma almacena en "x" por el numero de elementos del arraylist notas*/
        System.out.println("El promedio total es: " +x);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        double[] notas = new double[15];
        notas[0]=10.00d;
        notas[1]=5.51d;
        notas[2]=8.21d;
        notas[3]=3.63d;
        notas[4]=7.21d;
        notas[5]=6.15d;
        notas[6]=9.00d;
        notas[7]=8.00d;
        notas[8]=7.81d;
        notas[9]=8.05d;
        notas[10]=6.60d;
        notas[11]=4.15d;
        notas[12]=4.15d;
        notas[13]=4.15d;
        notas[14]=4.15d;
        
        double notaSuperior=0.00; /*parte un valor 0 para hallar una nota mas alta*/

        for(int i=0;i<notas.length;i++){
            if(notas[i]>notaSuperior){
                notaSuperior=notas[i];
            }
        }
        System.out.println("La nota mas alta es: " + notaSuperior);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        double[] notas = new double[15];
        notas[0]=10.00d;
        notas[1]=5.51d;
        notas[2]=8.21d;
        notas[3]=3.63d;
        notas[4]=7.21d;
        notas[5]=6.15d;
        notas[6]=9.00d;
        notas[7]=8.00d;
        notas[8]=7.81d;
        notas[9]=8.05d;
        notas[10]=6.60d;
        notas[11]=4.15d;
        notas[12]=4.15d;
        notas[13]=4.15d;
        notas[14]=4.15d;
        
        double notaSuperior=0.00; /*parte de un 0 para encontrar un valor mayor*/
        int posicionNota=0; 

        for(int i=0;i<notas.length;i++){ /*bucle for*/
            if(notas[i]>notaSuperior){
                notaSuperior=notas[i];
                posicionNota=i;
                
            }
        }
        System.out.println("La nota mas alta es: " + notaSuperior +" y la posicion es: " +posicionNota);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        
        ArrayList<Personas> personas = new ArrayList<>();

	Personas p1 = new Personas();
	p1.setNombre("Daniel");
	p1.setSexo("M");
	personas.add(p1);
		
	Personas p2 = new Personas();
	p2.setNombre("Alejandro");
	p2.setSexo("M");
	personas.add(p2);
		
	Personas p3 = new Personas();
	p3.setNombre("Carla");
	p3.setSexo("F");
	personas.add(p3);
		
	Personas p4 = new Personas();
	p4.setNombre("Maria");
	p4.setSexo("F");
	personas.add(p4);
		
	Personas p5 = new Personas();
	p5.setNombre("Mabel");
	p5.setSexo("F");
	personas.add(p5);
		
	ArrayList<Personas> listFemeninos = new ArrayList<Personas>();
        ArrayList<Personas> listMasculinos = new ArrayList<Personas>();
	
        Iterator<Personas> it = personas.iterator();
        
        while(it.hasNext()){
            Personas p = it.next();
            if(p.getSexo().equals("M")){
                listMasculinos.add(p);
            }else{
                listFemeninos.add(p);
            }
        }
        for(int x=0;x<listMasculinos.size();x++){
            System.out.println("Nombres masculinos: "+ listMasculinos.get(x).getNombre());
        }
        for(int z=0;z<listFemeninos.size();z++){
            System.out.println("Nombres femeninos: "+ listFemeninos.get(z).getNombre());
        }
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
